package sqlformatter

import postgresql "sql-formatter-go/languages/postgresql"

var postgresqlReservedSelectPhrases = []string{
	"SELECT [ALL | DISTINCT]",
}

var postgresqlReservedClausesPhrases = []string{
	"WITH [RECURSIVE]",
	"FROM",
	"WHERE",
	"GROUP BY [ALL | DISTINCT]",
	"HAVING",
	"WINDOW",
	"PARTITION BY",
	"ORDER BY",
	"LIMIT",
	"OFFSET",
	"FETCH {FIRST | NEXT}",
	"FOR {UPDATE | NO KEY UPDATE | SHARE | KEY SHARE} [OF]",
	"INSERT INTO",
	"VALUES",
	"DEFAULT VALUES",
	"SET",
	"RETURNING",
}

var postgresqlStandardOnelineClausesPhrases = []string{
	"CREATE [GLOBAL | LOCAL] [TEMPORARY | TEMP | UNLOGGED] TABLE [IF NOT EXISTS]",
}

var postgresqlTabularOnelineClausesPhrases = []string{
	"CREATE [OR REPLACE] [TEMP | TEMPORARY] [RECURSIVE] VIEW",
	"CREATE [MATERIALIZED] VIEW [IF NOT EXISTS]",
	"UPDATE [ONLY]",
	"WHERE CURRENT OF",
	"ON CONFLICT",
	"DELETE FROM [ONLY]",
	"DROP TABLE [IF EXISTS]",
	"ALTER TABLE [IF EXISTS] [ONLY]",
	"ALTER TABLE ALL IN TABLESPACE",
	"RENAME [COLUMN]",
	"RENAME TO",
	"ADD [COLUMN] [IF NOT EXISTS]",
	"DROP [COLUMN] [IF EXISTS]",
	"ALTER [COLUMN]",
	"SET DATA TYPE",
	"{SET | DROP} DEFAULT",
	"{SET | DROP} NOT NULL",
	"TRUNCATE [TABLE] [ONLY]",
	"SET SCHEMA",
	"AFTER",
	"ABORT",
	"ALTER AGGREGATE",
	"ALTER COLLATION",
	"ALTER CONVERSION",
	"ALTER DATABASE",
	"ALTER DEFAULT PRIVILEGES",
	"ALTER DOMAIN",
	"ALTER EVENT TRIGGER",
	"ALTER EXTENSION",
	"ALTER FOREIGN DATA WRAPPER",
	"ALTER FOREIGN TABLE",
	"ALTER FUNCTION",
	"ALTER GROUP",
	"ALTER INDEX",
	"ALTER LANGUAGE",
	"ALTER LARGE OBJECT",
	"ALTER MATERIALIZED VIEW",
	"ALTER OPERATOR",
	"ALTER OPERATOR CLASS",
	"ALTER OPERATOR FAMILY",
	"ALTER POLICY",
	"ALTER PROCEDURE",
	"ALTER PUBLICATION",
	"ALTER ROLE",
	"ALTER ROUTINE",
	"ALTER RULE",
	"ALTER SCHEMA",
	"ALTER SEQUENCE",
	"ALTER SERVER",
	"ALTER STATISTICS",
	"ALTER SUBSCRIPTION",
	"ALTER SYSTEM",
	"ALTER TABLESPACE",
	"ALTER TEXT SEARCH CONFIGURATION",
	"ALTER TEXT SEARCH DICTIONARY",
	"ALTER TEXT SEARCH PARSER",
	"ALTER TEXT SEARCH TEMPLATE",
	"ALTER TRIGGER",
	"ALTER TYPE",
	"ALTER USER",
	"ALTER USER MAPPING",
	"ALTER VIEW",
	"ANALYZE",
	"BEGIN",
	"CALL",
	"CHECKPOINT",
	"CLOSE",
	"CLUSTER",
	"COMMENT ON",
	"COMMIT",
	"COMMIT PREPARED",
	"COPY",
	"CREATE ACCESS METHOD",
	"CREATE [OR REPLACE] AGGREGATE",
	"CREATE CAST",
	"CREATE COLLATION",
	"CREATE [DEFAULT] CONVERSION",
	"CREATE DATABASE",
	"CREATE DOMAIN",
	"CREATE EVENT TRIGGER",
	"CREATE EXTENSION",
	"CREATE FOREIGN DATA WRAPPER",
	"CREATE FOREIGN TABLE",
	"CREATE [OR REPLACE] FUNCTION",
	"CREATE GROUP",
	"CREATE [UNIQUE] INDEX",
	"CREATE [OR REPLACE] [TRUSTED] [PROCEDURAL] LANGUAGE",
	"CREATE OPERATOR",
	"CREATE OPERATOR CLASS",
	"CREATE OPERATOR FAMILY",
	"CREATE POLICY",
	"CREATE [OR REPLACE] PROCEDURE",
	"CREATE PUBLICATION",
	"CREATE ROLE",
	"CREATE [OR REPLACE] RULE",
	"CREATE SCHEMA [AUTHORIZATION]",
	"CREATE [TEMPORARY | TEMP | UNLOGGED] SEQUENCE",
	"CREATE SERVER",
	"CREATE STATISTICS",
	"CREATE SUBSCRIPTION",
	"CREATE TABLESPACE",
	"CREATE TEXT SEARCH CONFIGURATION",
	"CREATE TEXT SEARCH DICTIONARY",
	"CREATE TEXT SEARCH PARSER",
	"CREATE TEXT SEARCH TEMPLATE",
	"CREATE [OR REPLACE] TRANSFORM",
	"CREATE [OR REPLACE] [CONSTRAINT] TRIGGER",
	"CREATE TYPE",
	"CREATE USER",
	"CREATE USER MAPPING",
	"DEALLOCATE",
	"DECLARE",
	"DISCARD",
	"DROP ACCESS METHOD",
	"DROP AGGREGATE",
	"DROP CAST",
	"DROP COLLATION",
	"DROP CONVERSION",
	"DROP DATABASE",
	"DROP DOMAIN",
	"DROP EVENT TRIGGER",
	"DROP EXTENSION",
	"DROP FOREIGN DATA WRAPPER",
	"DROP FOREIGN TABLE",
	"DROP FUNCTION",
	"DROP GROUP",
	"DROP IDENTITY",
	"DROP INDEX",
	"DROP LANGUAGE",
	"DROP MATERIALIZED VIEW [IF EXISTS]",
	"DROP OPERATOR",
	"DROP OPERATOR CLASS",
	"DROP OPERATOR FAMILY",
	"DROP OWNED",
	"DROP POLICY",
	"DROP PROCEDURE",
	"DROP PUBLICATION",
	"DROP ROLE",
	"DROP ROUTINE",
	"DROP RULE",
	"DROP SCHEMA",
	"DROP SEQUENCE",
	"DROP SERVER",
	"DROP STATISTICS",
	"DROP SUBSCRIPTION",
	"DROP TABLESPACE",
	"DROP TEXT SEARCH CONFIGURATION",
	"DROP TEXT SEARCH DICTIONARY",
	"DROP TEXT SEARCH PARSER",
	"DROP TEXT SEARCH TEMPLATE",
	"DROP TRANSFORM",
	"DROP TRIGGER",
	"DROP TYPE",
	"DROP USER",
	"DROP USER MAPPING",
	"DROP VIEW",
	"EXECUTE",
	"EXPLAIN",
	"FETCH",
	"GRANT",
	"IMPORT FOREIGN SCHEMA",
	"LISTEN",
	"LOAD",
	"LOCK",
	"MOVE",
	"NOTIFY",
	"OVERRIDING SYSTEM VALUE",
	"PREPARE",
	"PREPARE TRANSACTION",
	"REASSIGN OWNED",
	"REFRESH MATERIALIZED VIEW",
	"REINDEX",
	"RELEASE SAVEPOINT",
	"RESET [ALL|ROLE|SESSION AUTHORIZATION]",
	"REVOKE",
	"ROLLBACK",
	"ROLLBACK PREPARED",
	"ROLLBACK TO SAVEPOINT",
	"SAVEPOINT",
	"SECURITY LABEL",
	"SELECT INTO",
	"SET CONSTRAINTS",
	"SET ROLE",
	"SET SESSION AUTHORIZATION",
	"SET TRANSACTION",
	"SHOW",
	"START TRANSACTION",
	"UNLISTEN",
	"VACUUM",
}

var postgresqlReservedSetOperationsPhrases = []string{
	"UNION [ALL | DISTINCT]",
	"EXCEPT [ALL | DISTINCT]",
	"INTERSECT [ALL | DISTINCT]",
}

var postgresqlReservedJoinsPhrases = []string{
	"JOIN",
	"{LEFT | RIGHT | FULL} [OUTER] JOIN",
	"{INNER | CROSS} JOIN",
	"NATURAL [INNER] JOIN",
	"NATURAL {LEFT | RIGHT | FULL} [OUTER] JOIN",
}

var postgresqlReservedKeywordPhrasesPhrases = []string{
	"PRIMARY KEY",
	"GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY",
	"ON {UPDATE | DELETE} [NO ACTION | RESTRICT | CASCADE | SET NULL | SET DEFAULT]",
	"DO NOTHING",
	"AS MATERIALIZED",
	"{ROWS | RANGE | GROUPS} BETWEEN",
	"IS [NOT] DISTINCT FROM",
	"NULLS {FIRST | LAST}",
	"WITH ORDINALITY",
}

var postgresqlReservedDataTypePhrasesPhrases = []string{
	"[TIMESTAMP | TIME] {WITH | WITHOUT} TIME ZONE",
}

var postgresqlOperators = []string{
	"%",
	"^",
	"|/",
	"||/",
	"@",
	":=",
	"&",
	"|",
	"#",
	"~",
	"<<",
	">>",
	"~>~",
	"~<~",
	"~>=~",
	"~<=~",
	"@-@",
	"@@",
	"##",
	"<->",
	"&&",
	"&<",
	"&>",
	"<<|",
	"&<|",
	"|>>",
	"|&>",
	"<^",
	"^>",
	"?#",
	"?-",
	"?|",
	"?-|",
	"?||",
	"@>",
	"<@",
	"~=",
	"?",
	"@?",
	"?&",
	"->",
	"->>",
	"#>",
	"#>>",
	"#-",
	"=>",
	">>=",
	"<<=",
	"~~",
	"~~*",
	"!~~",
	"!~~*",
	"~",
	"~*",
	"!~",
	"!~*",
	"-|-",
	"||",
	"@@@",
	"!!",
	"^@",
	"<%",
	"%>",
	"<<%",
	"%>>",
	"<<->",
	"<->>",
	"<<<->",
	"<->>>",
	"::",
	":",
	"<#>",
	"<=>",
	"<+>",
	"<~>",
	"<%>",
}

var PostgresqlDialect = DialectOptions{
	Name: "postgresql",
	TokenizerOptions: TokenizerOptions{
		ReservedSelect: ExpandPhrases(postgresqlReservedSelectPhrases),
		ReservedClauses: append(append([]string{}, ExpandPhrases(postgresqlReservedClausesPhrases)...), append(append([]string{}, ExpandPhrases(postgresqlStandardOnelineClausesPhrases)...), ExpandPhrases(postgresqlTabularOnelineClausesPhrases)...)...),
		ReservedSetOperations: ExpandPhrases(postgresqlReservedSetOperationsPhrases),
		ReservedJoins: ExpandPhrases(postgresqlReservedJoinsPhrases),
		ReservedKeywordPhrases: ExpandPhrases(postgresqlReservedKeywordPhrasesPhrases),
		ReservedDataTypePhrases: ExpandPhrases(postgresqlReservedDataTypePhrasesPhrases),
		ReservedKeywords: postgresql.Keywords,
		ReservedDataTypes: postgresql.DataTypes,
		ReservedFunctionNames: postgresql.Functions,
		NestedBlockComments: true,
		ExtraParens: []string{"[]"},
		UnderscoresInNumbers: true,
		StringTypes: []QuoteType{
			PlainQuoteType("$$"),
			PrefixedQuoteType{Quote: PlainQuoteType("''-qq"), Prefixes: []string{"U&"}},
			PrefixedQuoteType{Quote: PlainQuoteType("''-qq-bs"), Prefixes: []string{"E"}, RequirePrefix: true},
			PrefixedQuoteType{Quote: PlainQuoteType("''-raw"), Prefixes: []string{"B", "X"}, RequirePrefix: true},
		},
		IdentTypes: []QuoteType{
			PrefixedQuoteType{Quote: PlainQuoteType("\"\"-qq"), Prefixes: []string{"U&"}},
		},
		IdentChars: &IdentChars{Rest: "$"},
		ParamTypes: &ParamTypes{Numbered: []string{"$"}},
		Operators: postgresqlOperators,
		OperatorKeyword: true,
	},
	FormatOptions: DialectFormatOptions{
		AlwaysDenseOperators: []string{"::", ":"},
		OnelineClauses: append(append([]string{}, ExpandPhrases(postgresqlStandardOnelineClausesPhrases)...), ExpandPhrases(postgresqlTabularOnelineClausesPhrases)...),
		TabularOnelineClauses: ExpandPhrases(postgresqlTabularOnelineClausesPhrases),
	},
}
